#!/usr/bin/env python3
"""Lane F — generate the machine-derived halves of BIBLIOGRAPHY.md from the two
provenance records, so no citation is hand-transcribed.

  meta/downloads.json        -> the CIPHER-SPACE half (academic literature, this lane)
  meta/press_provenance.json -> the PRESS half (re-derived from the mirrored archive)

Writes BIBLIOGRAPHY-GENERATED.md, which BIBLIOGRAPHY.md includes verbatim.
"""
import json, os, collections, io

D = os.path.dirname(os.path.abspath(__file__))
dl = json.load(io.open(os.path.join(D, 'meta', 'downloads.json'), encoding='utf-8'))
pv = json.load(io.open(os.path.join(D, 'meta', 'press_provenance.json'), encoding='utf-8'))

TOPIC_ORDER = [
    ('otp;derived-keystream', 'One-time-pad indistinguishability: true pad vs derived keystream'),
    ('keystream;distinguisher', 'One-time-pad indistinguishability: true pad vs derived keystream'),
    ('randomness-testing', 'One-time-pad indistinguishability: true pad vs derived keystream'),
    ('entropy-estimation', 'One-time-pad indistinguishability: true pad vs derived keystream'),
    ('running-key', 'Running-key and autokey cryptanalysis'),
    ('running-key;information-theory', 'Running-key and autokey cryptanalysis'),
    ('ngram-scoring;keytext-search', 'Running-key and autokey cryptanalysis'),
    ('unicity', 'Unicity distance: how much ciphertext before a solution is unique'),
    ('unicity;stego', 'Unicity distance: how much ciphertext before a solution is unique'),
    ('anti-repeat;smirnov', 'Anti-repeat constrained sequences (the doublet deficit)'),
    ('anti-repeat;carlitz', 'Anti-repeat constrained sequences (the doublet deficit)'),
    ('extreme-value;fwer', 'Extreme-value statistics and multiple testing over keyspace sweeps'),
    ('fwer', 'Extreme-value statistics and multiple testing over keyspace sweeps'),
    ('runic', 'Runic cryptography'),
    ('runic;signal-vs-noise', 'Runic cryptography'),
    ('ngram-scoring', 'Language-model scoring and search for classical ciphers'),
    ('ngram-scoring;short-ciphertext', 'Language-model scoring and search for classical ciphers'),
    ('ngram-scoring;lm-mismatch', 'Language-model scoring and search for classical ciphers'),
    ('homophonic;bayesian', 'Language-model scoring and search for classical ciphers'),
    ('search;ngram-scoring', 'Language-model scoring and search for classical ciphers'),
    ('search;metaheuristics', 'Search-based cryptanalysis (what a failed search proves)'),
    ('nulls;steganography', 'Nulls, interrupters and cipher+stego combinations'),
    ('unsolved-cipher-diagnosis', 'Diagnosing an unsolved cipher without solving it'),
    ('cipher-type-id', 'Diagnosing an unsolved cipher without solving it'),
    ('voynich', 'Diagnosing an unsolved cipher without solving it'),
    ('transcription', 'Transcription error as a cryptanalytic confound'),
    ('transcription;vision', 'Transcription error as a cryptanalytic confound'),
    ('corpus', 'Corpora and tooling'),
    ('tooling', 'Corpora and tooling'),
    ('historical', 'Corpora and tooling'),
    ('neural-cryptanalysis', 'Machine learning applied to classical ciphers'),
    ('epigraphy', 'Machine learning applied to classical ciphers'),
]
sec_of = {}
order = []
for t, s in TOPIC_ORDER:
    sec_of[t] = s
    if s not in order:
        order.append(s)

by_sec = collections.defaultdict(list)
for path, v in dl.items():
    if path == '_failures' or not isinstance(v, dict) or not v.get('path'):
        continue
    by_sec[sec_of.get(v.get('topic'), 'Other')].append(v)

out = []
out.append('<!-- GENERATED by mkbib.py from meta/downloads.json and meta/press_provenance.json. Do not hand-edit. -->\n')

out.append('## Cipher-space half — held academic literature\n')
n = sum(len(v) for v in by_sec.values())
out.append('%d items, all retrieved by this lane with recorded source URL, SHA-256 and retrieval UTC '
           '(`meta/downloads.json`). Every one is open access; nothing here was paywall-bypassed.\n' % n)
for s in order + [k for k in by_sec if k not in order]:
    items = by_sec.get(s)
    if not items:
        continue
    out.append('\n### %s\n' % s)
    for v in sorted(items, key=lambda x: (str(x.get('date')), str(x.get('title')))):
        auth = v.get('author') or '—'
        date = v.get('date') or 'n.d.'
        doi = ('DOI [%s](https://doi.org/%s)' % (v['doi'], v['doi'])) if v.get('doi') else 'no DOI'
        out.append('- **%s** — %s (%s). *%s*. %s.' % (v.get('title'), auth, date, v.get('venue') or '—', doi))
        out.append('  - PDF: `%s` · sha256 `%s` · %s B · retrieved %s' %
                   (v['path'], v['sha256'], v['bytes'], v.get('retrieved_utc')))
        out.append('  - Source: %s' % v.get('source_url'))
        if v.get('notes'):
            out.append('  - Relevance: %s' % v['notes'])

out.append('\n---\n')
out.append('## Press half — per-file provenance re-derived from the mirrored archive\n')
pdfs = [v for v in pv.values() if v.get('kind') == 'pdf']
both = [v for v in pdfs if v.get('source_url') and v.get('capture_date')]
out.append('%d files in `liber-primus/analysis/attribution/papers-archive/` (%d PDFs). '
           '**%d PDFs yielded both an original source URL and a capture date** from their '
           'print-to-PDF running header/footer (`meta/press_provenance.json`).\n'
           % (len(pv), len(pdfs), len(both)))
for v in sorted(both, key=lambda x: (x.get('capture_date') or '', x['file'])):
    out.append('- `%s` — captured **%s** from %s' % (v['file'], v['capture_date'], v['source_url']))
    out.append('  - sha256 `%s` · %s B' % (v['sha256'], v['bytes']))

nourl = [v for v in pdfs if not v.get('source_url')]
nodate = [v for v in pdfs if not v.get('capture_date')]
out.append('\n### Press files whose footer yielded no source URL (%d)\n' % len(nourl))
for v in sorted(nourl, key=lambda x: x['file']):
    out.append('- `%s` — sha256 `%s`' % (v['file'], v['sha256']))
out.append('\n### Press files whose footer yielded no capture date (%d)\n' % len(nodate))
for v in sorted(nodate, key=lambda x: x['file']):
    out.append('- `%s` — sha256 `%s`' % (v['file'], v['sha256']))

nonpdf = [v for v in pv.values() if v.get('kind') != 'pdf']
out.append('\n### Non-PDF files in the press archive (%d)\n' % len(nonpdf))
for v in sorted(nonpdf, key=lambda x: x['file']):
    out.append('- `%s` — %s B · sha256 `%s`' % (v['file'], v['bytes'], v['sha256']))

p = os.path.join(D, 'BIBLIOGRAPHY-GENERATED.md')
io.open(p, 'w', encoding='utf-8').write('\n'.join(out) + '\n')
print('wrote', p, os.path.getsize(p), 'bytes |', n, 'academic |', len(both), 'press with URL+date')
