"""Generate liber-primus/SOLVED-PAGES.json — the decoded text of every solved LP page.

"What do the solved Liber Primus pages actually say?" is one of the most common factual
questions about Cicada 3301, and the answers are scattered across wikis of varying quality
and Discord logs. This emits them as one JSON document.

Every plaintext here is **DERIVED BY RUNNING THE CIPHER**, not transcribed from a wiki. The
script decrypts each page from the canonical runes using the repo's own rig and records what
came out. That means the corpus cannot drift from what the code can actually reproduce, and
it inherits the trust anchor: if tests/validate.py passes, these strings are what the rig
produces from the ciphertext.

    python3 build_solved_pages.py
"""
import json, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
LP = os.path.abspath(os.path.join(HERE, "..", ".."))
ROOT = os.path.abspath(os.path.join(LP, ".."))
sys.path.insert(0, os.path.join(LP, "src"))
sys.path.insert(0, os.path.join(LP, "tests"))

from lp import gematria as gp, ciphers, corpus, solve, score as _score

OUT = os.path.join(LP, "SOLVED-PAGES.json")

# label, method, key, human title, provenance note
PAGES = [
    ("Runes - 01.jpg", "simple", None, "A WARNING",
     "Atbash. The book's opening warning."),
    ("05.jpg", "simple", None, "SOME WISDOM",
     "Direct transliteration, no key. States the puzzle's own theology of primes."),
    ("06.jpg", "simple", None, "A KOAN (the master and the student)",
     "Atbash plus a Caesar shift of 3."),
    ("03.jpg", "vigenere", "DIVINITY", "WELCOME",
     "Vigenere with key DIVINITY, plus interrupter runes that must be skipped."),
    ("14.jpg", "vigenere", "FIRFUMFERENFE", "A KOAN (the circumference)",
     "Vigenere with key FIRFUMFERENFE - 'CIRCUMFERENCE' written in the lossy runic "
     "alphabet, where C and F share a rune. The key is a pun on the alphabet itself."),
]


def brute_simple(idxs, scorer):
    """Search the small space of simple transforms, exactly as tests/validate.py does."""
    cands = []
    for atb in (False, True):
        base = ciphers.atbash_indices(idxs) if atb else idxs
        for k in range(gp.N):
            for sign in (-1, +1):
                out = [(c + sign * k) % gp.N for c in base]
                txt = gp.indices_to_translit(out)
                cands.append((f"{'atbash+' if atb else ''}shift{sign * k:+d}",
                              txt, scorer.score_norm(txt)))
    cands.sort(key=lambda c: -c[2])
    return cands[0]


def main():
    scorer = _score.default()
    out = []
    for label, kind, key, title, note in PAGES:
        page = corpus.page_by_label(label)
        if not page or not page["runes"]:
            print(f"!! {label}: no runes parsed")
            continue
        idxs = gp.runes_to_indices(page["runes"])
        if kind == "simple":
            method, txt, sc = brute_simple(idxs, scorer)
            n_int = 0
        else:
            stream = ciphers.repeat_key(gp.keyword_to_indices(key), len(idxs))
            res = solve.find_interrupters(page["runes"], stream, sign=-1,
                                          beam_width=500, scorer=scorer)
            txt, sc = res["plaintext"], res["score_norm"]
            n_int = res["n_interrupters"]
            method = f"vigenere({key})"
        up = "".join(c for c in txt.upper() if c.isalpha())
        out.append({
            "page_label": label,
            "title": title,
            "method": method,
            "key": key,
            "n_interrupters": n_int,
            "n_runes": len(idxs),
            "score_norm": round(sc, 3),
            "plaintext_transliteration": up,
            "note": note,
        })
        print(f"  {label:16s} {method:22s} score={sc:6.2f}  {up[:52]}")

    doc = {
        "$comment": "The decoded text of every solved Liber Primus page. DERIVED by running "
                    "the cipher over the canonical runes, not transcribed from a wiki. "
                    "Generated by liber-primus/analysis/handoff/build_solved_pages.py.",
        "how_to_reproduce": "python3 liber-primus/tests/validate.py",
        "reading_note":
            "The transliteration is LOSSY, which is why the text looks misspelled. The runic "
            "alphabet has 29 symbols and no K, Q, V or Z: K is written C, V is written U, and "
            "seven runes expand to two letters (TH EO NG OE AE IA EA). So 'KNOW' appears as "
            "'CNOW', 'BELIEVE' as 'BELIEUE', 'THINGS' as 'THNGS'. These are faithful outputs, "
            "not decoding errors.",
        "interrupter_note":
            "The rune F (index 0) sometimes acts as a skip marker rather than a letter. The "
            "count of interrupters found per page is recorded below; a decode that ignores "
            "them will not produce readable text.",
        "unsolved":
            "LP2 pages 0-54, totalling 12,956 runes, remain UNSOLVED. See PROBLEM.json.",
        "pages": out,
    }
    with open(OUT, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=1, ensure_ascii=False)
    print(f"\nwrote {os.path.relpath(OUT, ROOT)}  ({len(out)} solved pages)")


if __name__ == "__main__":
    main()
