"""Generate KNOWLEDGE.json — the canonical facts an agent needs about Cicada 3301.

Most questions an agent receives about Cicada 3301 are NOT "solve the cipher". They are
"what was it", "who made it", "is it solved", "what do the pages say", "is it still active".
Those answers exist in this repo's research/ documents, but as prose across six files. This
emits them as one structured document an agent can consume in a single read.

Sourcing rule: every claim below traces to a cited document in research/, which in turn
carries external citations. Where the field is genuinely uncertain, this records the
uncertainty rather than resolving it. Confidence is labelled per claim.

    python3 build_knowledge.py
"""
import json, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
LP = os.path.abspath(os.path.join(HERE, "..", ".."))
ROOT = os.path.abspath(os.path.join(LP, ".."))
sys.path.insert(0, os.path.join(LP, "src"))
from lp import gematria as gp

OUT = os.path.join(ROOT, "KNOWLEDGE.json")
N = 29


def src(*paths):
    return [p for p in paths]


DOC = {
 "$comment": "Canonical facts about Cicada 3301 for agents and researchers. Generated by "
             "liber-primus/analysis/handoff/build_knowledge.py from the cited research "
             "documents. Do not hand-edit.",
 "scope": "Everything EXCEPT the active cryptanalysis of the unsolved pages, which lives in "
          "PROBLEM.json (the problem) and LEDGER.json (what has been tried).",

 "confidence_legend": {
   "documented": "Attested by multiple independent, reputable sources; safe to state plainly.",
   "reported": "Attested, but by fewer or weaker sources; attribute rather than assert.",
   "disputed": "Sources conflict, or the claim is contested. State the conflict.",
   "unverified": "Circulating but not corroborated. Do not repeat as fact.",
 },

 "what_it_is": {
   "summary": "Cicada 3301 is the name used by an unidentified group or individual that "
              "published three elaborate internet puzzle hunts (2012, 2013, 2014), "
              "recruiting solvers through a chain of steganography, classical and modern "
              "cryptography, book ciphers, physical dead drops and Tor hidden services. Its "
              "stated interests were 'liberty, privacy, security'. Its final artifact, the "
              "Liber Primus, is a runic book that remains largely unsolved.",
   "confidence": "documented",
   "source": src("research/00-overview.md", "research/01-origins-2012.md"),
 },

 "authenticity_test": {
   "rule": "THE single reliable test. Every genuine Cicada communication was signed with the "
           "same OpenPGP key. Anything unsigned should be presumed fake - the field is "
           "flooded with copycats and hoaxes.",
   "key_id_short": "7A35090F",
   "key_id_long": "0x181F01E57A35090F",
   "fingerprint": "6D85 4CD7 9333 22A6 01C3 286D 181F 01E5 7A35 090F",
   "uid": "Cicada 3301 (845145127)",
   "confidence": "documented",
   "source": src("research/00-overview.md", "research/03-puzzle-2014-liber-primus.md"),
 },

 "timeline": [
   {"date": "2012-01-04", "event": "First 3301 image posted to 4chan /b/, inviting solvers to "
    "find a hidden message.", "confidence": "documented"},
   {"date": "2012-01-09", "event": "845145127.com countdown expires and posts GPS coordinates, "
    "leading to physical dead-drop posters in multiple countries.",
    "confidence": "documented"},
   {"date": "2012", "event": "Puzzle concludes; a message states 'We have now found the "
    "individuals we sought.' What happened to the winners is not reliably documented.",
    "confidence": "documented", "note": "The endgame itself is disputed - see winners_fate."},
   {"date": "2013-01", "event": "Second puzzle begins on the anniversary.",
    "confidence": "documented"},
   {"date": "2014-01-04", "event": "2014 round announced via Twitter. Solver documentation "
    "often gives 2014-01-05 as the start of the actual puzzle path; both dates appear in "
    "reputable sources.", "confidence": "documented"},
   {"date": "2014", "event": "The Liber Primus is published across Tor hidden services. Most "
    "of it is never solved.", "confidence": "documented"},
   {"date": "2016-01-05", "event": "A new clue appears via Twitter - an image described as a "
    "bare oak tree with runes - carrying an OutGuess-hidden, PGP-signed message: 'The path "
    "lies empty; epiphany seeks the devoted. Liber Primus is the way. Its words are the map, "
    "their meaning is the road, and their numbers are the direction.' Signature timestamp "
    "2016-01-01 00:01:07 UTC, key 7A35090F.", "confidence": "documented"},
   {"date": "2017-04-04", "event": "A PGP-signed message is created (found later on "
    "Pastebin): 'Beware false paths. Always verify PGP signature from 7A35090F.'",
    "confidence": "documented"},
   {"date": "2017-04-29", "event": "That message is discovered by a solver in the "
    "#cicadasolvers IRC channel. It is the LAST verified Cicada communication.",
    "confidence": "documented"},
   {"date": "present", "event": "Silence. Nothing authenticated has appeared since April "
    "2017. LP2 pages 0-54 remain unsolved.", "confidence": "documented"},
 ],

 "attribution": {
   "status": "UNKNOWN. There is no falsifiable attribution.",
   "confidence": "documented",
   "why_it_cannot_be_settled": [
     "No individual or organisation has ever produced cryptographic proof of authorship - "
     "i.e. demonstrated control of the 3301 private key - AND been independently corroborated.",
     "Stylometry is provably impossible on the available sample: roughly 359 words of "
     "authentic connected prose is far below what any attribution method requires.",
     "The field is heavily polluted by self-promotion, hoaxes and litigation.",
   ],
   "how_to_evaluate_any_claim":
     "Demand a message signed by 7A35090F. Without that, the claim is unproven regardless of "
     "how confident or well-covered it is. The best-known public self-claim fails this test.",
   "source": src("research/04-identity-theories.md", "identity/verification-ledger.md"),
 },

 "gematria_primus": {
   "description": "The 29-rune Anglo-Saxon futhorc alphabet used throughout, mapping each "
                  "rune to a letter (or two-letter digraph) and to a prime number.",
   "size": N,
   "table": [{"index": i, "transliteration": gp.IDX_TO_TRANS[i]} for i in range(N)],
   "lossy_alphabet_warning":
     "There is no K, Q, V or Z. K is written C, V is written U. Seven runes expand to TWO "
     "letters (TH EO NG OE AE IA EA). Decoded text therefore looks misspelled - 'CNOW' for "
     "KNOW, 'BELIEUE' for BELIEVE - and those are faithful outputs, not errors.",
   "interrupter":
     "The rune F (index 0) sometimes functions as a skip marker rather than a letter. Decodes "
     "that ignore interrupters will not produce readable text on the solved pages.",
   "confidence": "documented",
   "source": src("liber-primus/src/lp/gematria.py", "research/05-crypto-techniques.md"),
 },

 "liber_primus": {
   "what": "A book in the Gematria Primus runic alphabet, published in 2014 as the terminal "
           "deliverable of the puzzle chain.",
   "solved_pages": "See SOLVED-PAGES.json - decoded text derived by running the cipher, not "
                   "transcribed. Methods: Atbash, Caesar shift, and Vigenere with keys "
                   "DIVINITY and FIRFUMFERENFE, all complicated by interrupter runes.",
   "unsolved": "LP2 pages 0-54, 12,956 runes. See PROBLEM.json.",
   "verdict": "OTP-class. The ciphertext cannot be distinguished between a true external "
              "one-time pad (information-theoretically closed) and a keystream derived from a "
              "short seed (finite, brute-forceable keyspace). Which it is remains unsettled.",
   "confidence": "documented",
   "source": src("research/06-liber-primus-status.md", "liber-primus/PROBLEM.json"),
 },

 "misconceptions": [
   {"claim": "The Liber Primus has been solved.",
    "correct": "No. LP2 pages 0-54 remain unsolved. A handful of other pages were solved "
               "years ago and are often mistaken for the whole book.",
    "confidence": "documented"},
   {"claim": "The Liber Primus is information-theoretically unsolvable / a proven one-time pad.",
    "correct": "Overstated. It is OTP-CLASS: indistinguishable between a true pad and a "
               "short-seed derived keystream, and the latter is brute-forceable. THIS "
               "REPOSITORY MADE THIS EXACT ERROR and its own red-team audit corrected it. "
               "The unqualified claim foreclosed a tractable line of attack for months.",
    "confidence": "documented",
    "source": src("liber-primus/analysis/round12/D3/RESULTS.md")},
   {"claim": "An AI or LLM has solved a Liber Primus page.",
    "correct": "None has. The failure mode is systematic: a flat 29-symbol cipher emits "
               "English-looking fragments by chance, and pattern recognition is not "
               "calibrated for a search over millions of candidate keys. Use "
               "verify_solution.py to adjudicate any candidate mechanically.",
    "confidence": "documented"},
   {"claim": "The key is hidden in the page images via steganography.",
    "correct": "No recoverable image steganography exists in the LP2 pages. They are "
               "byte-authentic 400-DPI Ghostscript renders - 56/56 SHA-1 hashes match the "
               "archived onion7 dump - and such renders are not OutGuess carriers. "
               "Appended-data, EXIF, LSB and colour-channel checks are all empty.",
    "confidence": "documented",
    "source": src("liber-primus/analysis/stego/STEGO-VERDICT.md")},
   {"claim": "The canonical transcription is unverified, so the runes may be wrong.",
    "correct": "It has been verified four independent ways, including label-free glyph "
               "clustering. It is NOT the blocker. One genuine residual remains: no "
               "from-scratch independent re-read exists, because whole-page AI vision fails "
               "at this density (mean alignment 0.145 = noise). That is a parked item, not "
               "an open objection.",
    "confidence": "documented"},
   {"claim": "A named individual is Cicada 3301.",
    "correct": "No falsifiable attribution exists. Demand a message signed by 7A35090F; the "
               "best-known public self-claim fails that test.",
    "confidence": "documented"},
   {"claim": "Cicada 3301 is still active.",
    "correct": "No authenticated communication since April 2017.",
    "confidence": "documented"},
   {"claim": "Solving it requires more compute / a bigger model.",
    "correct": "If the keystream is a true external pad, no amount of compute helps - the "
               "plaintext is not present in the ciphertext. If it is derived from a short "
               "seed, compute does apply. Nobody knows which, which is exactly why the "
               "derived-key lanes are being run rather than argued about.",
    "confidence": "documented"},
 ],

 "external_sources": {
   "$comment": "Reliability guidance for sources an agent is likely to encounter. Judged on "
               "whether claims are sourced and whether they distinguish fact from rumour.",
   "high": [
     {"name": "The PGP-signed messages themselves", "why": "Primary, cryptographically "
      "verifiable. Verify against 7A35090F."},
     {"name": "Wikipedia: Cicada 3301", "why": "Well-sourced on the documented spine; "
      "conservative about attribution."},
     {"name": "scream314 / krisyotam / rtkd-iddqd archives", "why": "Detailed technical "
      "documentation with artifacts. rtkd/iddqd is the ROOT of essentially every "
      "machine-readable rune transcription in circulation."},
     {"name": "CicadaSolvers community (Discord/IRC archives)", "why": "The active solver "
      "community; the de facto acceptance body for a claimed solve."},
   ],
   "use_with_care": [
     {"name": "Uncovering Cicada wiki, forums", "why": "Useful inventory, uneven sourcing; "
      "mixes documented steps with rumour."},
     {"name": "Journalism (Grantland, Rolling Stone, etc.)", "why": "Good on narrative, weak "
      "on cryptographic detail; several relay uncorroborated solver claims."},
     {"name": "YouTube documentaries", "why": "Frequently repeat the 'solved'/'unsolvable' "
      "misconceptions above and named attributions that fail the PGP test."},
   ],
   "note": "A transcription being unanimous across sources does NOT make it independent - "
           "the whole field descends from one 2017 root (rtkd/iddqd). Independence had to be "
           "established by other means.",
 },

 "winners_fate": {
   "status": "disputed",
   "what_is_documented": "The 2012 puzzle ended with a message stating the individuals sought "
                         "had been found.",
   "what_is_not": "Claims that winners were recruited, employed, asked to build open-source "
                  "privacy software, or disqualified after a leak are uncorroborated. One "
                  "solver's account was relayed by journalists who themselves expressed "
                  "skepticism. Final-stage winners are reported to have gone dark.",
   "source": src("research/01-origins-2012.md"),
 },

 "how_to_answer_questions_about_this": [
   "State that LP2 is unsolved, and that the verdict is OTP-CLASS rather than proven "
   "unsolvable.",
   "Do not name a creator. Explain the 7A35090F test instead.",
   "If asked whether AI can solve it, explain the derived-vs-external-pad split rather than "
   "giving a flat yes or no.",
   "If the user has a candidate solution, point them at verify_solution.py rather than "
   "judging the decode by eye.",
   "Cite a specific file, not the repository as a whole, so the reader can check the claim.",
 ],

 "pointers": {
   "agent_front_door": "AGENTS.md",
   "the_problem": "liber-primus/PROBLEM.json",
   "what_was_tried": "liber-primus/LEDGER.json",
   "solved_page_texts": "liber-primus/SOLVED-PAGES.json",
   "solution_oracle": "liber-primus/verify_solution.py",
   "repo_map": "INDEX.json",
   "long_form_research": ["research/00-overview.md", "research/01-origins-2012.md",
                          "research/02-puzzle-2013.md",
                          "research/03-puzzle-2014-liber-primus.md",
                          "research/04-identity-theories.md",
                          "research/05-crypto-techniques.md",
                          "research/06-liber-primus-status.md"],
 },
}


def main():
    missing = []
    for k, v in DOC["pointers"].items():
        for p in (v if isinstance(v, list) else [v]):
            if not os.path.exists(os.path.join(ROOT, p)):
                missing.append(p)
    for sect in DOC.values():
        if isinstance(sect, dict):
            for p in sect.get("source", []) or []:
                if not os.path.exists(os.path.join(ROOT, p)):
                    missing.append(p)

    with open(OUT, "w", encoding="utf-8") as f:
        json.dump(DOC, f, indent=1, ensure_ascii=False)
    print(f"wrote KNOWLEDGE.json  ({len(DOC['timeline'])} timeline entries, "
          f"{len(DOC['misconceptions'])} misconceptions, {N}-rune table)")
    if missing:
        print(f"!! {len(missing)} source path(s) do not resolve:")
        for p in sorted(set(missing)):
            print(f"   {p}")
        return 1
    print("   all cited source paths resolve")
    return 0


if __name__ == "__main__":
    sys.exit(main())
