/* ROUND 19 / G2 -- glibc srand48/drand48 reference.
 *
 * Perl 5.14.2 on a glibc host defines (config_h.SH, generated by Configure):
 *     #define Drand01()        drand48()
 *     #define seedDrand01(x)   srand48((Rand_seed_t)x)     [Rand_seed_t = long]
 * so this program calls exactly the functions the era Perl called.  Gate B
 * compares its output against the installed perl's rand(), which retires the
 * 5.40-vs-5.14 version risk by measurement instead of by argument.
 *
 *   ref_drand48 SEED N   ->  N lines of "%.17g"
 */
#include <stdio.h>
#include <stdlib.h>

int main(int argc, char **argv)
{
    if (argc < 3) { fprintf(stderr, "usage: ref_drand48 SEED N\n"); return 2; }
    long seed = strtoul(argv[1], NULL, 10);
    int  n    = atoi(argv[2]);
    srand48(seed);
    for (int i = 0; i < n; i++)
        printf("%.17g\n", drand48());
    return 0;
}
