"""Statistical profile of the unsolved Liber Primus pages.

Compares the unsolved runic text against four baselines:
  1. random uniform over 29 symbols (theoretical)
  2. English plaintext mapped onto Gematria Primus (what a SOLVED page looks like)
  3. a solved page's CIPHERTEXT (Vigenère, short key) — still polyalphabetic
  4. the unsolved corpus itself (aggregate + per page)

Writes analysis/STATS.md and prints a summary.

Run: PYTHONUTF8=1 python analysis/run_stats.py
"""
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))
from lp import gematria as gp, stats, corpus  # noqa

HERE = os.path.dirname(__file__)
KRIS = os.path.normpath(os.path.join(HERE, "..", "data", "krisyotam_runes.txt"))
OUT = os.path.join(HERE, "STATS.md")


def load_pages():
    """Split the krisyotam single-file transcription on '%' page breaks."""
    txt = open(KRIS, encoding="utf-8").read()
    segs = txt.split("%")
    pages = []
    for s in segs:
        idxs = gp.runes_to_indices(s)
        if idxs:
            pages.append(idxs)
    return pages


def english_baseline():
    """Map a chunk of archaic English onto Gematria Primus indices, the way the
    book itself would encode plaintext (greedy multi-rune matching)."""
    kjv = os.path.normpath(os.path.join(HERE, "..", "data", "kjv.txt"))
    import re
    t = re.sub(r"[^A-Za-z]", "", open(kjv, encoding="utf-8", errors="ignore").read())
    return gp.keyword_to_indices(t[5000:5000 + 6000])


def main():
    pages = load_pages()
    # last two LP2 pages (AN END, PARABLE) are solved; rest unsolved
    unsolved = [i for p in pages[:-2] for i in p]
    solved_plain = english_baseline()
    welcome = corpus.page_by_label("03.jpg")
    solved_cipher = gp.runes_to_indices(welcome["runes"]) if welcome else []

    rows = []
    rows.append(("random uniform (theory)", {"n": "-", "ioc_norm": 1.0,
                 "doublet_rate_pct": round(100 / gp.N, 3), "doublets": "-",
                 "chi2_uniform": round(gp.N - 1, 1), "entropy_bits": round(
                     __import__("math").log2(gp.N), 4)}))
    rows.append(("English→Gematria (solved-page plaintext)", stats.summary(solved_plain)))
    rows.append(("WELCOME ciphertext (Vigenère, key=8)", stats.summary(solved_cipher)))
    rows.append(("UNSOLVED LP2 pages (aggregate)", stats.summary(unsolved)))

    lines = ["# Liber Primus — Statistical Profile of the Unsolved Pages\n",
             f"Generated by `analysis/run_stats.py`. Alphabet size N={gp.N}. "
             f"Unsolved corpus: {len(unsolved)} runes across {len(pages) - 2} pages.\n",
             "## Baseline comparison\n",
             "| corpus | n | IoC·N | doublet % | doublets | χ² vs uniform | entropy (bits) |",
             "|---|---|---|---|---|---|---|"]
    for name, s in rows:
        lines.append(f"| {name} | {s['n']} | {s['ioc_norm']} | "
                     f"{s['doublet_rate_pct']} | {s['doublets']} | "
                     f"{s['chi2_uniform']} | {s['entropy_bits']} |")

    # interpretation
    rnd = 100 / gp.N
    un = stats.summary(unsolved)
    lines += ["\n## What this says\n",
              f"- **IoC·N = {un['ioc_norm']}** (random ≈ 1.0, monoalphabetic English ≈ "
              f"{rows[1][1]['ioc_norm']}). Near 1.0 ⇒ a strong polyalphabetic / "
              "running-key cipher, not a simple substitution.",
              f"- **Doublet rate = {un['doublet_rate_pct']}%** vs random {rnd:.3f}% "
              f"and English {rows[1][1]['doublet_rate_pct']}%. ",
              f"- **Entropy = {un['entropy_bits']} bits** vs max {__import__('math').log2(gp.N):.3f}.",
              ]

    # Kasiski on aggregate unsolved
    ks = stats.kasiski(unsolved)
    top = ks.most_common(15)
    lines += ["\n## Kasiski — repeated-trigram spacings (aggregate)\n",
              "Spacing : count (look for a dominant small factor = key period)\n",
              "```"]
    for sp, c in sorted(top, key=lambda x: -x[1]):
        lines.append(f"{sp:6d} : {c}")
    lines.append("```")

    # per-page table
    lines += ["\n## Per-page (LP2 ordering; last two are the solved AN END / PARABLE)\n",
              "| page | n | IoC·N | doublet % | entropy |",
              "|---|---|---|---|---|"]
    for i, p in enumerate(pages):
        s = stats.summary(p)
        lines.append(f"| {i} | {s['n']} | {s['ioc_norm']} | "
                     f"{s['doublet_rate_pct']} | {s['entropy_bits']} |")

    open(OUT, "w", encoding="utf-8").write("\n".join(lines) + "\n")

    print(f"pages parsed: {len(pages)} | unsolved runes: {len(unsolved)}")
    print(f"{'corpus':42s} {'IoC·N':>7} {'dbl%':>7} {'entropy':>8}")
    for name, s in rows:
        print(f"{name:42s} {str(s['ioc_norm']):>7} {str(s['doublet_rate_pct']):>7} "
              f"{str(s['entropy_bits']):>8}")
    print(f"\nKasiski top spacings: {top[:8]}")
    print(f"\nwrote {OUT}")


if __name__ == "__main__":
    main()
