#!/usr/bin/env python3
"""Round 27 / P2 -- S2 (keyskip1 'exact') acceptance checks against the DEPLOYED C engine.

PREREG S2 gate: the 'exact' lane may not contribute a null until it has its own planted
control + V1-style vector file, validated against the C engine. This script runs both
checks through the engine's REAL sweep code path (`--plan` -> run_lane -> screen_one ->
decode_seed with pair=0) using the UNMODIFIED deployed binary `P1-engine/grind27`, in a
SEPARATE run dir (never touches P1-engine/run/ or the live sweep process):

  S2-V1 (vector parity): a plan of 64 width-1 'exact' lanes, one per seed of
    P0-spec/vectors_s2.json. Each lane's top_<lane>.json records that seed's pmax at
    %.17g (works below the candidate bar too). Compare vs the Python reference:
    rel diff must be <= 1e-6 (measured: exact to double precision).
    ks128 parity for these seeds is already established by the S1 V1 gate (same seed
    list; the keystream does not depend on the relation).

  S2-V2 (planted control through the sweep): build engine_plant.dat -- identical to
    P1-engine/engine.dat except CSCREEN := the S2 plant cipher (first 120 runes of
    vectors_s2.json planted_selftest.cipher_idx, enciphered under encipher_keyskip,
    the ONE-draw rejection loop) and the 64 V1 VEC entries regenerated by the Python
    pipeline for that cipher under the launch self-test's pair relation (so the
    launch-time V1+V2 self-test stays a REAL check, not a bypassed one). Then micro-
    sweep the band [745, 809) (plant seed 777 mid-band) under relation 'exact':
    seed 777 MUST land in candidates.jsonl with pmax matching Python to <= 1e-9 and
    clearing the S2 claim bar 7.6341931878728095 (=> HIT-CANDIDATE.json raised).
    Finally the flagged seed is adjudicated by the REAL Python 3-clause gate
    (hitfn20, preset='exact', strict truth_idx): HIT=True, recovery >= 0.90 required.

Both engine invocations require GRIND27_S2_CONTROL_OK=1 (the engine refuses 'exact'
lanes otherwise); this script IS the validation that gate demands, so it sets the
variable for its own child processes only.

Run:  cd liber-primus/analysis/round27/P2-harness/s2check && nice -n 15 python3 check_s2.py
Exit: 0 = all PASS, 1 = any FAIL. Single-threaded engine calls (--threads 1).
"""
import json, os, subprocess, sys

HERE = os.path.dirname(os.path.abspath(__file__))
R27 = os.path.abspath(os.path.join(HERE, "..", ".."))
LP = os.path.abspath(os.path.join(R27, "..", ".."))
P1 = os.path.join(R27, "P1-engine")
GRIND = os.path.join(P1, "grind27")
DAT = os.path.join(P1, "engine.dat")
VEC_S2 = os.path.join(R27, "P0-spec", "vectors_s2.json")

R25 = os.path.join(LP, "analysis", "round25", "compute-tail")
sys.path.insert(0, R25)
import runner  # noqa: R25 pipeline verbatim (pulls in driftbeam/adjudicate/hitfn20 paths)
import driftbeam as DB
import adjudicate as AD
import hitfn20 as H

CLAIM_BAR_EXACT = 7.6341931878728095
PLANT_BAND = (745, 809)                 # plant seed 777 mid-band (index 32 of 64)
ENV = dict(os.environ, GRIND27_S2_CONTROL_OK="1")


def run_grind(args):
    cmd = ["nice", "-n", "15", GRIND] + args
    r = subprocess.run(cmd, cwd=HERE, env=ENV, capture_output=True, text=True)
    return r


def lane_plan_entry(name, a, b):
    return {"lane": name, "reducer": "random29", "relation": "exact", "offset": 0,
            "from": a, "to": b, "claim_bar": CLAIM_BAR_EXACT}


# --------------------------------------------------------------- S2-V1 parity
def check_parity(v):
    plan = [lane_plan_entry("S2V%03d" % i, r["seed"], r["seed"] + 1)
            for i, r in enumerate(v["seed_vectors"])]
    plan_path = os.path.join(HERE, "parity_plan.json")
    json.dump(plan, open(plan_path, "w"), indent=1)
    rundir = os.path.join(HERE, "parity_run")
    os.makedirs(rundir, exist_ok=True)
    r = run_grind(["--plan", plan_path, "--run-dir", rundir, "--threads", "1"])
    if r.returncode != 0:
        print(r.stdout[-4000:], r.stderr[-2000:])
        return False, {"error": "engine rc=%d" % r.returncode}
    worst_rel, worst_seed, n_ok = 0.0, None, 0
    for i, row in enumerate(v["seed_vectors"]):
        top = json.load(open(os.path.join(rundir, "top_S2V%03d.json" % i)))
        assert len(top) == 1 and top[0]["seed"] == row["seed"], (i, top)
        c_pm, py_pm = float(top[0]["pmax"]), float(row["pmax"])
        rel = abs(c_pm - py_pm) / max(1.0, abs(py_pm))
        if rel > worst_rel:
            worst_rel, worst_seed = rel, row["seed"]
        if rel <= 1e-6:
            n_ok += 1
    ok = n_ok == len(v["seed_vectors"])
    return ok, {"n_ok": n_ok, "n": len(v["seed_vectors"]),
                "worst_rel_diff": worst_rel, "worst_seed": worst_seed}


# ------------------------------------------------------- S2-V2 planted control
def build_plant_dat(v):
    """engine_plant.dat = engine.dat with CSCREEN := plant cipher[:120] and the V1 VEC
    block regenerated (Python pair-relation decodes of that cipher), so the engine's
    launch self-test remains a genuine parity check on the plant cipher."""
    plantC = v["planted_selftest"]["cipher_idx"][:120]
    seeds = [r["seed"] for r in v["seed_vectors"]]
    vec_lines = []
    for w in seeds:
        K = runner.word_stream(w, runner.L_SCREEN * 6 + 64)
        d = DB.beam_decode(plantC, K, sign=-1, o=0, beam_w=runner.SCREEN_BEAM_W,
                           **DB.PRESETS["pair"])
        a = AD.adjudicate(d["plain_idx"], translit=d.get("translit"))
        vec_lines.append("VEC %d %r %r %d %d %d"
                         % (w, float(a["pmax"]), float(d["score"]),
                            d["ptr_end"], d["n_skips"], d["nchars"]))
        vec_lines.append("KS " + " ".join(map(str, runner.word_stream(w, 128))))
        vec_lines.append("PLAIN " + " ".join(map(str, d["plain_idx"])))

    src = open(DAT).read().splitlines()
    out, i = [], 0
    while i < len(src):
        ln = src[i]
        key = ln.split(" ", 1)[0] if ln else ""
        if key == "CSCREEN":
            out.append("CSCREEN %d" % len(plantC))
            out.append(" ".join(map(str, plantC)))
            i += 2                                    # skip old count line + data line
        elif key == "NVEC":
            out.append("NVEC %d" % len(seeds))
            out.extend(vec_lines)
            i += 1
            while i < len(src) and src[i].split(" ", 1)[0] in ("VEC", "KS", "PLAIN"):
                i += 1                                # drop the original VEC block
        else:
            out.append(ln)
            i += 1
    path = os.path.join(HERE, "engine_plant.dat")
    open(path, "w").write("\n".join(out) + "\n")
    return path


def check_plant(v):
    dat = build_plant_dat(v)
    plan_path = os.path.join(HERE, "plant_plan.json")
    json.dump([lane_plan_entry("S2PLANT", *PLANT_BAND)], open(plan_path, "w"), indent=1)
    rundir = os.path.join(HERE, "plant_run")
    os.makedirs(rundir, exist_ok=True)
    r = run_grind(["--data", dat, "--plan", plan_path, "--run-dir", rundir,
                   "--threads", "1"])
    launch_selftest_pass = "SELF-TEST: PASS" in r.stdout
    if r.returncode != 0:
        print(r.stdout[-4000:], r.stderr[-2000:])
        return False, {"error": "engine rc=%d" % r.returncode}

    cands = [json.loads(x) for x in open(os.path.join(rundir, "candidates.jsonl"))]
    flagged = [c for c in cands if c["seed"] == 777]
    py_pm = float(v["planted_stage_a"]["pmax"])
    c_pm = float(flagged[0]["pmax"]) if flagged else None
    hits_path = os.path.join(rundir, "HIT-CANDIDATE.json")
    hits = json.load(open(hits_path)) if os.path.exists(hits_path) else {"hits": []}
    hit_flag = any(h["seed"] == 777 for h in hits["hits"])

    # the real chain: take the C-flagged seed, adjudicate with the REAL Python gate
    gate = None
    if flagged:
        seed = flagged[0]["seed"]
        C = v["planted_selftest"]["cipher_idx"]
        truth = v["planted_selftest"]["truth_idx"]
        K = runner.word_stream(seed, runner.L_HIT * 6 + 64)
        dec = H.HitDecode(C=C, K=K, o=0, preset="exact", n_round_adjudicated=10 ** 6,
                          truth_idx=truth[:len(C)])
        vv = H.evaluate(dec)
        gate = {"hit": bool(vv.hit), "recovery": round(vv.recovery, 4),
                "heldout": round(vv.heldout_recovery, 4),
                "pmax": round(vv.pmax, 4), "bar": round(vv.bar, 4)}

    ok = (launch_selftest_pass and bool(flagged)
          and abs(c_pm - py_pm) <= 1e-9
          and c_pm >= CLAIM_BAR_EXACT and hit_flag
          and gate is not None and gate["hit"] and gate["recovery"] >= 0.90
          and gate["heldout"] >= 0.90)
    return ok, {"launch_selftest_pass": launch_selftest_pass,
                "flagged_777": bool(flagged), "c_pmax": c_pm, "py_pmax": py_pm,
                "abs_diff": None if c_pm is None else abs(c_pm - py_pm),
                "clears_claim_bar": None if c_pm is None else c_pm >= CLAIM_BAR_EXACT,
                "hit_candidate_flag_raised": hit_flag,
                "other_seeds_in_band_flagged": [c["seed"] for c in cands
                                               if c["seed"] != 777],
                "python_3clause_gate": gate}


def main():
    v = json.load(open(VEC_S2))
    ok1, r1 = check_parity(v)
    print("S2-V1 vector parity (64 width-1 'exact' lanes, real sweep path): %s %s"
          % ("PASS" if ok1 else "FAIL", json.dumps(r1)))
    ok2, r2 = check_plant(v)
    print("S2-V2 planted control (exact-relation plant, mid-band micro-sweep): %s %s"
          % ("PASS" if ok2 else "FAIL", json.dumps(r2)))
    print("OVERALL: %s" % ("PASS" if ok1 and ok2 else "FAIL"))
    return 0 if ok1 and ok2 else 1


if __name__ == "__main__":
    sys.exit(main())
