#!/usr/bin/env python3
"""Round 27 / P1 -- flatten the frozen P0 artifacts into files grind27.c can load.

Inputs (never re-derived here; provenance is P0):
  * analysis/round27/P0-spec/vectors.json   -- ciphertext slice, constants, 64 seed
    vectors, planted stage-A construct (all generated by make_vectors.py from the
    R25 pipeline verbatim)
  * analysis/round19/I2/models/panel.npz    -- the SAME panel.npz that generated
    vectors.json (LM table, 9 x 24389 float32)
  * data/english_quadgrams.txt              -- referenced by path only (C parses it)

Outputs (next to this file):
  * engine.dat      -- line-oriented text: constants, C_SCREEN, planted construct,
                       64 reference vectors. Doubles are written as Python repr so
                       C strtod() reconstructs bit-identical values.
  * panel_lm.f32    -- 9 x 24389 little-endian float32, row-major (register-major),
                       exactly SPEC section 4. sha256 recorded in engine.dat.

Regenerate:  python3 export_data.py
"""
import hashlib
import json
import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
LP = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
VECTORS = os.path.join(LP, "analysis", "round27", "P0-spec", "vectors.json")
PANEL = os.path.join(LP, "analysis", "round19", "I2", "models", "panel.npz")
QGRAM = os.path.join(LP, "data", "english_quadgrams.txt")

OUT_DAT = os.path.join(HERE, "engine.dat")
OUT_LM = os.path.join(HERE, "panel_lm.f32")


def main():
    v = json.load(open(VECTORS))
    c = v["constants"]
    assert c["PRESET"] == "pair" and c["MODE"] == "random29"
    assert c["L_SCREEN"] == 120 and c["SCREEN_BEAM_W"] == 64
    assert c["sign"] == -1 and c["offset"] == 0

    d = np.load(PANEL, allow_pickle=False)
    regs = [str(s) for s in d["registers"]]
    assert regs == c["registers"], (regs, c["registers"])
    lm = np.ascontiguousarray(d["LM"].reshape(len(regs), -1).astype(np.float32))
    assert lm.shape == (9, 29 ** 3), lm.shape
    blob = lm.astype("<f4").tobytes()          # row-major, register-major, LE
    with open(OUT_LM, "wb") as f:
        f.write(blob)
    sha = hashlib.sha256(blob).hexdigest()

    L = []
    L.append("GRIND27DATA 1")
    L.append("PANEL_SHA256 " + sha)
    L.append("PANEL_PATH " + OUT_LM)
    L.append("QGRAM_PATH " + QGRAM)
    L.append("QGRAM_TOTAL %d" % c["quadgram"]["total"])
    L.append("QGRAM_FLOOR " + c["quadgram"]["floor"])
    L.append("QGRAM_NENTRIES %d" % c["quadgram"]["n_entries"])
    L.append("NREG %d" % len(regs))
    L.append("MU " + " ".join(c["panel_mu_n120"]))
    L.append("SD " + " ".join(c["panel_sd_n120"]))
    L.append("CAND_BAR %r" % float(c["SCREEN_BAR"]))
    L.append("CLAIM_BAR_PAIR " + c["claim_bar_pair_1e6"])
    L.append("CLAIM_BAR_EXACT 7.6341931878728095")   # SPEC S2: vecbeam.keyskip1+I2|pmax|L120
    cs = v["ciphertext"]["C_SCREEN"]
    L.append("CSCREEN %d" % len(cs))
    L.append(" ".join(map(str, cs)))
    pa = v["planted_stage_a"]
    L.append("PLANT_SEED %d" % pa["seed"])
    L.append("PLANT_PMAX " + pa["pmax"])
    L.append("PLANT_CIPHER %d" % len(pa["cipher_idx_120"]))
    L.append(" ".join(map(str, pa["cipher_idx_120"])))
    L.append("PLANT_PLAIN %d" % len(pa["plain_idx"]))
    L.append(" ".join(map(str, pa["plain_idx"])))
    sv = v["seed_vectors"]
    L.append("NVEC %d" % len(sv))
    for r in sv:
        L.append("VEC %d %s %s %d %d %d"
                 % (r["seed"], r["pmax"], r["beam_score"],
                    r["ptr_end"], r["n_skips"], r["nchars"]))
        L.append("KS " + " ".join(map(str, r["ks128"])))
        L.append("PLAIN " + " ".join(map(str, r["plain_idx"])))
    L.append("END")
    with open(OUT_DAT, "w") as f:
        f.write("\n".join(L) + "\n")
    print("wrote", OUT_DAT, "and", OUT_LM)
    print("panel_lm.f32 sha256:", sha)


if __name__ == "__main__":
    sys.exit(main())
