#!/usr/bin/env python3
"""REPRODUCE A WARNING -- Liber Primus page `Runes - 01.jpg`.

Method: ATBASH (reflect every rune index i -> 28-i). No key, no interrupters.
The book's opening warning.

Standalone: no import from `liber-primus/src`. Reads only raw data files.
Run from anywhere:  PYTHONUTF8=1 python analysis/reproduce/reproduce_page_runes_01.py

GENERATED by analysis/reproduce/build_reproduce_scripts.py -- edit that, not this.
"""
import os
import re
import sys
import math
import hashlib

ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
LPDATA = os.path.join(ROOT, "liber-primus", "data")

# --------------------------------------------------------- Gematria Primus
GEMATRIA = [
    (0, "\u16a0", "F", 2), (1, "\u16a2", "U", 3), (2, "\u16a6", "TH", 5),
    (3, "\u16a9", "O", 7), (4, "\u16b1", "R", 11), (5, "\u16b3", "C", 13),
    (6, "\u16b7", "G", 17), (7, "\u16b9", "W", 19), (8, "\u16bb", "H", 23),
    (9, "\u16be", "N", 29), (10, "\u16c1", "I", 31), (11, "\u16c4", "J", 37),
    (12, "\u16c7", "EO", 41), (13, "\u16c8", "P", 43), (14, "\u16c9", "X", 47),
    (15, "\u16cb", "S", 53), (16, "\u16cf", "T", 59), (17, "\u16d2", "B", 61),
    (18, "\u16d6", "E", 67), (19, "\u16d7", "M", 71), (20, "\u16da", "L", 73),
    (21, "\u16dd", "NG", 79), (22, "\u16df", "OE", 83), (23, "\u16de", "D", 89),
    (24, "\u16aa", "A", 97), (25, "\u16ab", "AE", 101), (26, "\u16a3", "Y", 103),
    (27, "\u16e1", "IA", 107), (28, "\u16e0", "EA", 109),
]
N = 29
RUNE_TO_IDX = {r: i for (i, r, _t, _p) in GEMATRIA}
IDX_TO_TRANS = {i: t for (i, _r, t, _p) in GEMATRIA}
INTERRUPTER = "\u16a0"  # the F rune
_TRANS_SORTED = sorted(((t, i) for (i, _r, t, _p) in GEMATRIA), key=lambda x: -len(x[0]))


def runes_only(text):
    return "".join(c for c in text if c in RUNE_TO_IDX)


def to_indices(runes):
    return [RUNE_TO_IDX[c] for c in runes]


def to_translit(idxs):
    return "".join(IDX_TO_TRANS[i % N] for i in idxs)


def keyword_to_indices(word):
    """Parse a Latin keyword into Gematria indices, longest transliteration first."""
    s = word.upper().replace(" ", "")
    out, i = [], 0
    while i < len(s):
        for t, idx in _TRANS_SORTED:
            if s.startswith(t, i):
                out.append(idx)
                i += len(t)
                break
        else:
            alias = {"V": 1, "K": 5, "Z": 15, "Q": 5}.get(s[i])
            if alias is None:
                raise ValueError("cannot map %r" % s[i])
            out.append(alias)
            i += 1
    return out


# ------------------------------------------------------------- raw artifact
def runes_from_scream314(label):
    """First runic code block under the '## <label>' header of the canonical
    transcription markdown. This is the raw artifact; nothing is retyped."""
    path = os.path.join(LPDATA, "scream314_lp.md")
    lines = open(path, encoding="utf-8").read().splitlines()
    start = None
    for i, ln in enumerate(lines):
        if ln.startswith("## ") and label in ln[3:]:
            start = i
            break
    if start is None:
        raise SystemExit("label %r not found in %s" % (label, path))
    end = len(lines)
    for j in range(start + 1, len(lines)):
        if lines[j].startswith("## "):
            end = j
            break
    blocks, cur = [], []
    for ln in lines[start + 1:end]:
        if ln.startswith("    ") or ln.startswith("\t"):
            cur.append(ln.strip())
        elif ln.strip() == "" and cur:
            cur.append("")
        else:
            if cur:
                blocks.append("\n".join(cur))
                cur = []
    if cur:
        blocks.append("\n".join(cur))
    for b in blocks:
        r = runes_only(b)
        if r:
            return r
    raise SystemExit("no runic block under %r" % label)


def runes_from_relikd(filename):
    return runes_only(open(os.path.join(LPDATA, "sources", filename), encoding="utf-8").read())


# ------------------------------------------------------------------ scorer
class Quadgram(object):
    """English-likeness by quadgram log10-probability. Higher = more English."""

    def __init__(self):
        self.d = {}
        total = 0
        with open(os.path.join(LPDATA, "english_quadgrams.txt"), encoding="ascii") as f:
            for line in f:
                q, c = line.split()
                c = int(c)
                self.d[q] = c
                total += c
        lt = math.log10(total)
        for q in self.d:
            self.d[q] = math.log10(self.d[q]) - lt
        self.floor = math.log10(0.01) - lt

    def score(self, text):
        t = re.sub(r"[^A-Z]", "", text.upper())
        if len(t) < 4:
            return -999.0
        return sum(self.d.get(t[i:i + 4], self.floor) for i in range(len(t) - 3))

    def score_norm(self, text):
        t = re.sub(r"[^A-Z]", "", text.upper())
        n = len(t) - 3
        return self.score(t) / n if n > 0 else -999.0


# ------------------------------------------------------------------ ciphers
def atbash(idxs):
    return [(N - 1) - c for c in idxs]


def shift(idxs, k, sign=-1):
    return [(c + sign * k) % N for c in idxs]


def repeat_key(key_indices, length):
    return [key_indices[i % len(key_indices)] for i in range(length)]


def decrypt_with_interrupters(runes, stream, scorer, sign=-1, beam_width=500):
    """Beam search over which F runes are nulls, for ANY keystream.

    Rule (as confirmed by the solved pages): only the F rune is ever a null,
    not every F is, a null F is dropped from the plaintext and does NOT advance
    the keystream. The beam keeps the `beam_width` best-scoring skip/keep
    prefixes at every F, so it scales past 2**n brute force.
    """
    beams = [(frozenset(), 0, [])]
    f_seen = 0
    for ch in runes:
        c0 = RUNE_TO_IDX[ch]
        if ch == INTERRUPTER:
            nxt = []
            for iset, j, dec in beams:
                nxt.append((iset | {f_seen}, j, dec))                       # null
                nxt.append((iset, j + 1, dec + [IDX_TO_TRANS[(c0 + sign * stream[j]) % N]]))
            f_seen += 1
            nxt.sort(key=lambda b: scorer.score("".join(b[2])), reverse=True)
            beams = nxt[:beam_width]
        else:
            beams = [(iset, j + 1, dec + [IDX_TO_TRANS[(c0 + sign * stream[j]) % N]])
                     for iset, j, dec in beams]
    beams.sort(key=lambda b: scorer.score("".join(b[2])), reverse=True)
    iset, _j, dec = beams[0]
    return "".join(dec), sorted(iset)


def sieve_primes(count):
    primes, cand = [], 2
    while len(primes) < count:
        if all(cand % p for p in primes if p * p <= cand):
            primes.append(cand)
        cand += 1
    return primes


def canon(s):
    """Collapse the alphabet's genuine ambiguities before word matching:
    C=K, U=V, S=Z, Q=C. The runic alphabet cannot distinguish these."""
    s = re.sub(r"[^A-Z]", "", s.upper())
    for a, b in (("K", "C"), ("V", "U"), ("Z", "S"), ("Q", "C")):
        s = s.replace(a, b)
    return s


def report(label, title, method, runes, plaintext, expect, extra=""):
    idxs = to_indices(runes)
    print("page          : %s" % label)
    print("title         : %s" % title)
    print("method        : %s%s" % (method, (" " + extra) if extra else ""))
    print("n_runes       : %d" % len(runes))
    print("interrupters  : %d literal F runes" % idxs.count(0))
    print("rune sha256   : %s" % hashlib.sha256(runes.encode("utf-8")).hexdigest())
    print("")
    up = canon(plaintext)
    for i in range(0, len(up), 78):
        print("  " + up[i:i + 78])
    print("")
    missing = [w for w in expect if canon(w) not in up]
    for w in expect:
        print("  %-14s %s" % (w, "FOUND" if canon(w) not in missing else "MISSING"))
    assert not missing, "expected words missing from plaintext: %s" % missing
    print("")
    print("PASS  %s -- %s" % (label, title))
    return 0

EXPECT = ['AWARNNG', 'BELIEVE', 'FROMTHIS', 'TRUE', 'SACRED', 'NUMBERS']

def main():
    runes = runes_from_scream314("Runes - 01.jpg")
    assert len(runes) == 184, len(runes)
    idxs = to_indices(runes)
    plain = atbash(idxs)
    txt = to_translit(plain)
    return report("Runes - 01.jpg", "A WARNING", "atbash (i -> 28-i), shift 0",
                  runes, txt, EXPECT)


if __name__ == "__main__":
    raise SystemExit(main())
